sage_combo_track_relin_conservative:
  Config: config_camcalib.yaml
  Module: sageslam-dev
  NumRuns: 1
  Parameters:
    enable_gui: 'false'
    mode: mono
    rgb_idx:
    - 0
    - 541
    verbose: 1
