cotracker_model: cotracker_stride_4_wind_8
cotracker_window_size: 8
depth_estimator: constant
depth_scale: 3.0
global_ba_iterations: 10
img_height: -1
img_width: -1
keyframe_decision: subsample
keyframe_subsample: 4
local_ba_size: 30
localization_track_num: 50
lumen_mask_high_threshold: 0.95
lumen_mask_low_threshold: 0.05
minimum_new_points: 0
past_frame_size: 5
point_resample_cooldown: 1
point_sampler: uniform
pose_guesser: last_pose
ransac_localization: true
section_length: 13
tracked_point_num_max: 2000
tracked_point_num_min: 200
tracking_ba_iterations: 20
update_localized_pose: false
